project:
  type: website
  render:
    - "*.qmd"
    - "!local/"
    - "!slides/"

website:
  favicon: resources/favicon.png
  title: "ADCOM"
  navbar:
    background: "#786fa6"
    search: true
    right:
      - icon: github
        href: https://github.com/stat-teaching/adcom
        aria-label: GitHub

author: 
  - name: "Filippo Gambarota PhD"
    email: filippo.gambarota@unipd.it
    twitter: fgambarota
    github: filippogambarota
    orcid: "0000-0002-6666-1747"

institute: "Universit√† di Padova"

execute: 
  freeze: auto

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

bibliography: "https://raw.githubusercontent.com/filippogambarota/bib-database/main/references.bib"
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl"
